services:

  devdays-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  devdays-frontend:
    build:
      context: ../../dev-days-25-frontend 
      dockerfile: Dockerfile
      args:
        NODE_PUBLIC_API_URL: http://devdays-app:3000/api/v1
    restart: unless-stopped
    ports:
      - "8080:3000"
    networks:
      - backend

  devdays-mongo:
    image: mongo:6.0
    restart: unless-stopped
    # Just for MongoDB Compass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - db

  devdays-app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: devdays-app:latest
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGO_URI: mongodb://devdays-mongo:27017/isadevdays2025
      OPENAI_API_KEY2: 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
    ports:
      - "3000:3000"
      - "9464:9464"
    depends_on:
      - devdays-mongo
    networks:
      - backend
      - db
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3003:3000" # Entraremos por el 3003 para no chocar con nada
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
  db: